apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: challenge
  labels:
    role: api
spec:
  selector:
    role: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
