apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: challenge
  labels:
    role: frontend
    env: challenge
spec:
  selector:
    role: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
