apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: challenge
  labels:
    role: database
    env: challenge
spec:
  selector:
    role: database
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
